[workspace]
resolver = "2"
members = [
    "basics/authentication",
    "basics/login",
    "basics/variables",
    "projects/cli-app",
    "async-mt",
    "ay-aw-conc",
    "raas",
    "best-practices",
    "zero2prod"
]
