[package]
name = "cli-app"
version = "0.1.0"
edition = "2021"

[dependencies]
authentication = { path = "../../basics/authentication" }
login = { path = "../../basics/login" }
clap = { version = "4.3", features = ["derive"] }
