[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4"
expand = "0.3.0"
reqwest = "0.12.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-macros = "2.4.0"
