[package]
name = "ay-aw-conc"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.138"
anyhow = "1.0.96"
thiserror = "2.0.11"
